#!/usr/bin/env node
// Small, deterministic runner recipes used by the Content Runners starter
// templates. They deliberately emit only the JSON contract consumed by the
// worker, so a new runner can be dry-run before it is connected to real data.

const value = (args, name) => {
  const index = args.indexOf(name);
  return index < 0 ? undefined : args[index + 1];
};

export function buildTemplate(template, { prompt = '', now = new Date().toISOString() } = {}) {
  const sourceUrl = process.env.SWARTZIT_RUNNER_SOURCE_URL || 'https://stoverparc.org/';
  const requestedPrompt = String(prompt || 'Replace this prompt with the content you want the runner to produce.').trim();

  if (template === 'smoke') {
    return {
      title: 'Swartzit runner smoke test',
      body: `This post was generated by a disabled starter runner at ${now}. It is safe to test and should be replaced before enabling a production schedule.`,
      source_url: sourceUrl
    };
  }

  if (template === 'prompt') {
    return {
      title: 'Scheduled prompt draft',
      body: `${requestedPrompt}\n\nGenerated by the Swartzit starter runner at ${now}.`,
      source_url: sourceUrl
    };
  }

  if (template === 'batch') {
    return {
      posts: [
        { title: 'Starter batch · one', body: `First example from a bounded runner batch. Generated at ${now}.`, source_url: sourceUrl },
        { title: 'Starter batch · two', body: `Second example from the same bounded runner batch. Generated at ${now}.`, source_url: sourceUrl }
      ]
    };
  }

  throw new Error(`Unknown starter template: ${template}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const template = value(args, '--template') || 'smoke';
  const prompt = process.env.RUNNER_PROMPT || '';
  try {
    process.stdout.write(`${JSON.stringify(buildTemplate(template, { prompt }))}\n`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
